Clean up vendor dir

diff --git a/vendor/k8s.io/kubernetes/cluster/gce/trusty/node.yaml b/vendor/k8s.io/kubernetes/cluster/gce/trusty/node.yaml
--- a/vendor/k8s.io/kubernetes/cluster/gce/trusty/node.yaml
+++ b/vendor/k8s.io/kubernetes/cluster/gce/trusty/node.yaml
@@ -1,6 +1,35 @@
-From nobody Tue Aug 11 10:13:54 2015
+From nobody Thu Mar 10 10:33:00 2016
 Content-Type: multipart/mixed; boundary="===================================="
 MIME-Version: 1.0
+
+--====================================
+MIME-Version: 1.0
+Content-Type: text/upstart-job; charset="us-ascii"
+Content-Transfer-Encoding: 7bit
+Content-Disposition: attachment; filename="kube-install-minion.conf"
+
+#upstart-job
+
+description "Download and install k8s binaries and configurations"
+
+start on cloud-config
+
+script
+	set -o errexit
+	set -o nounset
+
+	# Fetch the script for installing nodes binary and configuration files.
+	curl --fail --silent --show-error \
+		-H "X-Google-Metadata-Request: True" \
+		-o /etc/kube-configure.sh \
+		http://metadata.google.internal/computeMetadata/v1/instance/attributes/configure-sh
+	. /etc/kube-configure.sh
+	echo "Downloading kube-env file"
+	download_kube_env
+	. /etc/kube-env
+	echo "Install kube nodes binary and configuration files"
+	install_kube_binary_config
+end script
 
 --====================================
 MIME-Version: 1.0
@@ -12,90 +41,24 @@ Content-Disposition: attachment; filename="kube-env.conf"
 
 description "Prepare kube node environment"
 
-start on cloud-config
+start on stopped kube-install-minion
 
 script
 	set -o errexit
 	set -o nounset
 
-	# Set the hostname to the short version.
-	short_hostname=$(hostname -s)
-	hostname $short_hostname
-
-	# We have seen that GCE image may have strict host firewall rules which drop
-	# most inbound/forwarded packets. In such a case, add rules to accept all
-	# TCP/UDP packets.
-	if iptables -L INPUT | grep "Chain INPUT (policy DROP)" > /dev/null; then
-		echo "Add rules to accpet all inbound TCP/UDP packets"
-		iptables -A INPUT -w -p TCP -j ACCEPT
-		iptables -A INPUT -w -p UDP -j ACCEPT
-	fi
-	if iptables -L FORWARD | grep "Chain FORWARD (policy DROP)" > /dev/null; then
-		echo "Add rules to accpet all forwarded TCP/UDP packets"
-		iptables -A FORWARD -w -p TCP -j ACCEPT
-		iptables -A FORWARD -w -p UDP -j ACCEPT
-	fi
-	# Create required directories.
-	mkdir -p /var/lib/kubelet
-	mkdir -p /var/lib/kube-proxy
-	mkdir -p /etc/kubernetes/manifests
-
-	# Fetch kube-env from GCE metadata server.
-	curl --fail --silent --show-error \
-		-H "X-Google-Metadata-Request: True" \
-		-o /tmp/kube-env-yaml \
-		http://metadata.google.internal/computeMetadata/v1/instance/attributes/kube-env
-	# Convert the yaml format file into a shell-style file.
-	eval $(python -c '''
-import pipes,sys,yaml
-for k,v in yaml.load(sys.stdin).iteritems():
-  print "readonly {var}={value}".format(var = k, value = pipes.quote(str(v)))
-''' < /tmp/kube-env-yaml > /etc/kube-env)
-
-	 #Create the kubelet kubeconfig file.
+	. /etc/kube-configure-helper.sh
 	. /etc/kube-env
-	if [ -z "${KUBELET_CA_CERT:-}" ]; then
-		KUBELET_CA_CERT="${CA_CERT}"
-	fi
-	cat > /var/lib/kubelet/kubeconfig << EOF
-apiVersion: v1
-kind: Config
-users:
-- name: kubelet
-  user:
-    client-certificate-data: ${KUBELET_CERT}
-    client-key-data: ${KUBELET_KEY}
-clusters:
-- name: local
-  cluster:
-    certificate-authority-data: ${KUBELET_CA_CERT}
-contexts:
-- context:
-    cluster: local
-    user: kubelet
-  name: service-account-context
-current-context: service-account-context
-EOF
-
-	# Create the kube-proxy config file.
-	cat > /var/lib/kube-proxy/kubeconfig << EOF
-apiVersion: v1
-kind: Config
-users:
-- name: kube-proxy
-  user:
-    token: ${KUBE_PROXY_TOKEN}
-clusters:
-- name: local
-  cluster:
-    certificate-authority-data: ${CA_CERT}
-contexts:
-- context:
-    cluster: local
-    user: kube-proxy
-  name: service-account-context
-current-context: service-account-context
-EOF
+	echo "Configuring hostname"
+	config_hostname
+	echo "Configuring IP firewall rules"
+	config_ip_firewall
+	echo "Creating required directories"
+	create_dirs
+	echo "Creating kubelet kubeconfig file"
+	create_kubelet_kubeconfig
+	echo "Creating kube-proxy kubeconfig file"
+	create_kubeproxy_kubeconfig
 end script
 
 --====================================
@@ -108,23 +71,14 @@ Content-Disposition: attachment; filename="kube-install-packages.conf"
 
 description "Install packages needed to run kubernetes"
 
-start on cloud-config
+start on stopped kube-install-minion
 
 script
 	set -o errexit
 	set -o nounset
 
-	apt-get update
-	# Install docker and brctl if they are not in the image.
-	if ! which docker > /dev/null; then
-  	echo "Do not find docker. Install it."
-		# We should install the docker that passes qualification. At present, it is version 1.7.1.
-		curl -sSL https://get.docker.com/ubuntu/ | DOCKER_VERSION=1.7.1 sh
-	fi
-	if ! which brctl > /dev/null; then
-		echo "Do not find brctl. Install it."
-		apt-get install --yes bridge-utils
-	fi
+	. /etc/kube-configure-helper.sh
+	install_critical_packages
 end script
 
 --====================================
@@ -143,87 +97,8 @@ script
 	set -o errexit
 	set -o nounset
 
-	# Socat and nsenter are not required for spinning up a cluster. We move the
-	# installation here to be in parallel with the cluster creation.
-	if ! which socat > /dev/null; then
-		echo "Do not find socat. Install it."
-		apt-get install --yes socat
-	fi
-	if ! which nsenter > /dev/null; then
-		echo "Do not find nsenter. Install it."
-		# Note: this is an easy way to install nsenter, but may not be the fastest way.
-		# In addition, this may not be a trusted source. So, replace it if we have a
-		# better solution.
-		docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
-	fi
-end script
-
---====================================
-MIME-Version: 1.0
-Content-Type: text/upstart-job; charset="us-ascii"
-Content-Transfer-Encoding: 7bit
-Content-Disposition: attachment; filename="kube-install-minion.conf"
-
-#upstart-job
-
-description "Download and install k8s binaries and configurations"
-
-start on stopped kube-env
-
-script
-	set -o errexit
-	set -o nounset
-
-	. /etc/kube-env
-	# For a testing cluster, we pull kubelet and kube-proxy binaries, and place them
-	# in /usr/local/bin. For a non-test cluster, we use the binaries pre-installed
-	# in the image, or pull and place them in /usr/bin if they are not pre-installed.
-	BINARY_PATH="/usr/bin/"
-	if [ "${TEST_CLUSTER:-}" = "true" ]; then
-		BINARY_PATH="/usr/local/bin/"
-	fi
-	if ! which kubelet > /dev/null || ! which kube-proxy > /dev/null || [ "${TEST_CLUSTER:-}" = "true" ]; then
-		cd /tmp
-		k8s_sha1="${SERVER_BINARY_TAR_URL##*/}.sha1"
-		echo "Downloading k8s tar sha1 file ${k8s_sha1}"
-		curl -Lo "${k8s_sha1}" --connect-timeout 20 --retry 6 --retry-delay 2 "${SERVER_BINARY_TAR_URL}.sha1"
-		k8s_tar="${SERVER_BINARY_TAR_URL##*/}"
-		echo "Downloading k8s tar file ${k8s_tar}"
-		curl -Lo "${k8s_tar}" --connect-timeout 20 --retry 6 --retry-delay 2 "${SERVER_BINARY_TAR_URL}"
-		# Validate hash.
-		actual=$(sha1sum ${k8s_tar} | awk '{ print $1 }') || true
-		if [ "${actual}" != "${SERVER_BINARY_TAR_HASH}" ]; then
-			echo "== ${k8s_tar} corrupted, sha1 ${actual} doesn't match expected ${SERVER_BINARY_TAR_HASH} =="
-		else
-			echo "Validated ${SERVER_BINARY_TAR_URL} SHA1 = ${SERVER_BINARY_TAR_HASH}"
-		fi
-		tar xzf "/tmp/${k8s_tar}" -C /tmp/ --overwrite
-		cp /tmp/kubernetes/server/bin/kubelet ${BINARY_PATH}
-		cp /tmp/kubernetes/server/bin/kube-proxy ${BINARY_PATH}
-		rm -rf "/tmp/kubernetes"
-		rm "/tmp/${k8s_tar}"
-		rm "/tmp/${k8s_sha1}"
-	fi
-
-	# Put saltbase configuration files in /etc/saltbase. We will use the add-on yaml files.
-	mkdir -p /etc/saltbase
-	cd /etc/saltbase
-	salt_sha1="${SALT_TAR_URL##*/}.sha1"
-	echo "Downloading Salt tar sha1 file ${salt_sha1}"
-	curl -Lo "${salt_sha1}" --connect-timeout 20 --retry 6 --retry-delay 2 "${SALT_TAR_URL}.sha1"
-	salt_tar="${SALT_TAR_URL##*/}"
-	echo "Downloading Salt tar file ${salt_tar}"
-	curl -Lo "${salt_tar}" --connect-timeout 20 --retry 6 --retry-delay 2 "${SALT_TAR_URL}"
-	# Validate hash.
-	actual=$(sha1sum ${salt_tar} | awk '{ print $1 }') || true
-	if [ "${actual}" != "${SALT_TAR_HASH}" ]; then
-		echo "== ${salt_tar} corrupted, sha1 ${actual} doesn't match expected ${SALT_TAR_HASH} =="
-	else
-		echo "Validated ${SALT_TAR_URL} SHA1 = ${SALT_TAR_HASH}"
-	fi
-	tar xzf "/etc/saltbase/${salt_tar}" -C /etc/saltbase/ --overwrite
-	rm "/etc/saltbase/${salt_sha1}"
-	rm "/etc/saltbase/${salt_tar}"
+	. /etc/kube-configure-helper.sh
+	install_additional_packages
 end script
 
 --====================================
@@ -236,7 +111,7 @@ Content-Disposition: attachment; filename="kubelet.conf"
 
 description "Run kubelet service"
 
-start on stopped kube-install-minion and stopped kube-install-packages
+start on stopped kube-install-packages and stopped kube-env
 
 respawn
 
@@ -244,16 +119,14 @@ script
 	set -o errexit
 	set -o nounset
 
+	echo "Start kubelet upstart job"
+	. /etc/kube-configure-helper.sh
 	. /etc/kube-env
-	ARGS="--v=2"
-	if [ -n "${KUBELET_TEST_ARGS:-}" ]; then
-		ARGS="${KUBELET_TEST_ARGS}"
-	fi
-	BINARY_PATH="/usr/bin/kubelet"
-	if [ "${TEST_CLUSTER:-}" = "true" ]; then
-		BINARY_PATH="/usr/local/bin/kubelet"
-	fi
-	${BINARY_PATH} \
+	# Assemble command line flags based on env variables, which will put the string
+	# of flags in variable KUBELET_CMD_FLAGS.
+	assemble_kubelet_flags
+
+	/usr/bin/kubelet \
 		--api-servers=https://${KUBERNETES_MASTER_NAME} \
 		--enable-debugging-handlers=true \
 		--cloud-provider=gce \
@@ -263,47 +136,14 @@ script
 		--cluster-domain=${DNS_DOMAIN} \
 		--configure-cbr0=true \
 		--cgroup-root=/ \
-		--system-container=/system \
-		${ARGS}
+		--system-cgroups=/system \
+		--runtime-cgroups=/docker-daemon \
+		--kubelet-cgroups=/kubelet \
+		--babysit-daemons=true \
+		${KUBELET_CMD_FLAGS} 1>>/var/log/kubelet.log 2>&1
 end script
 
 # Wait for 10s to start kubelet again.
-post-stop exec sleep 10
-
---====================================
-MIME-Version: 1.0
-Content-Type: text/upstart-job; charset="us-ascii"
-Content-Transfer-Encoding: 7bit
-Content-Disposition: attachment; filename="kube-proxy.conf"
-
-#upstart-job
-
-description "Start kube-proxy service"
-
-start on stopped kube-install-minion and stopped kube-install-packages
-
-respawn
-
-script
-	set -o errexit
-	set -o nounset
-
-	. /etc/kube-env
-	ARGS="--v=2"
-	if [ -n "${KUBEPROXY_TEST_ARGS:-}" ]; then
-		ARGS="${KUBEPROXY_TEST_ARGS}"
-	fi
-	BINARY_PATH="/usr/bin/kube-proxy"
-	if [ "${TEST_CLUSTER:-}" = "true" ]; then
-		BINARY_PATH="/usr/local/bin/kube-proxy"
-	fi
-	${BINARY_PATH} \
-		--master=https://${KUBERNETES_MASTER_NAME} \
-		--kubeconfig=/var/lib/kube-proxy/kubeconfig \
-		${ARGS}
-end script
-
-# Wait for 10s to start kube-proxy again.
 post-stop exec sleep 10
 
 --====================================
@@ -316,31 +156,70 @@ Content-Disposition: attachment; filename="kube-docker.conf"
 
 description "Restart docker daemon"
 
-# The condition "stopped kube-install-additional-packages" is to avoid
-# breaking nsenter installation, which is through a docker container.
-# It can be removed if we find a better way to install nsenter.
-start on started kubelet and stopped kube-install-additional-packages
+start on started kubelet
 
 script
 	set -o errexit
 	set -o nounset
 
+	. /etc/kube-configure-helper.sh
 	. /etc/kube-env
-	# Assemble docker deamon options
-	DOCKER_OPTS="-p /var/run/docker.pid --bridge=cbr0 --iptables=false --ip-masq=false"
-	if [ "${TEST_CLUSTER:-}" = "true" ]; then
-		DOCKER_OPTS="${DOCKER_OPTS} --log-level=debug"
+	restart_docker_daemon
+end script
+
+--====================================
+MIME-Version: 1.0
+Content-Type: text/upstart-job; charset="us-ascii"
+Content-Transfer-Encoding: 7bit
+Content-Disposition: attachment; filename="kube-proxy.conf"
+
+#upstart-job
+
+description "Start kube-proxy static pod"
+
+start on stopped kube-docker
+
+script
+	set -o errexit
+	set -o nounset
+
+	. /etc/kube-configure-helper.sh
+	. /etc/kube-env
+	prepare_log_file "/var/log/kube-proxy.log"
+	# Load the docker image from file /run/kube-docker-files/kube-proxy.tar.
+	echo "Try to load docker image file kube-proxy.tar"
+	timeout 30 docker load -i /run/kube-docker-files/kube-proxy.tar
+	# Copy the manifest to /tmp to manipulate
+	tmp_file="/tmp/kube-proxy.manifest"
+	cp -f /run/kube-manifests/kubernetes/kube-proxy.manifest ${tmp_file}
+	# Remove the lines of salt configuration and replace variables with values.
+	# NOTE: Changes to variable names in cluster/saltbase/salt/kube-proxy/kube-proxy.manifest
+	# may break this upstart job.
+	sed -i "/^ *{%/d" ${tmp_file}
+	kubeconfig="--kubeconfig=\/var\/lib\/kube-proxy\/kubeconfig"
+	kube_docker_registry="gcr.io\/google_containers"
+	if [ -n "${KUBE_DOCKER_REGISTRY:-}" ]; then
+		kube_docker_registry=${KUBE_DOCKER_REGISTRY}
 	fi
-	echo "DOCKER_OPTS=\"${DOCKER_OPTS} ${EXTRA_DOCKER_OPTS}\"" > /etc/default/docker
-	# Make sure the network interface cbr0 is created before restarting docker daemon
-	while ! [ -L /sys/class/net/cbr0 ]; do
-		echo "Sleep 1 second to wait for cbr0"
-		sleep 1
-	done
-	initctl restart docker
-	# Remove docker0
-	ifconfig docker0 down
-	brctl delbr docker0
+	kube_proxy_docker_tag=$(cat /run/kube-docker-files/kube-proxy.docker_tag)
+	test_args=""
+	if [ -n "${KUBEPROXY_TEST_ARGS:-}" ]; then
+		test_args="${KUBEPROXY_TEST_ARGS}"
+	fi
+	log_level="--v=2"
+	if [ -n "${KUBEPROXY_TEST_LOG_LEVEL:-}" ]; then
+		log_level="${KUBEPROXY_TEST_LOG_LEVEL}"
+	fi
+	api_servers="--master=https:\/\/${KUBERNETES_MASTER_NAME}"
+	sed -i -e "s/{{kubeconfig}}/${kubeconfig}/g" ${tmp_file}
+	sed -i -e "s/{{pillar\['kube_docker_registry'\]}}/${kube_docker_registry}/g" ${tmp_file}
+	sed -i -e "s/{{pillar\['kube-proxy_docker_tag'\]}}/${kube_proxy_docker_tag}/g" ${tmp_file}
+	sed -i -e "s/{{test_args}}/${test_args}/g" ${tmp_file}
+	sed -i -e "s/{{ cpurequest }}/20m/g" ${tmp_file}
+	sed -i -e "s/{{log_level}}/${log_level}/g" ${tmp_file}
+	sed -i -e "s/{{api_servers_with_port}}/${api_servers}/g" ${tmp_file}
+
+	mv -f ${tmp_file} /etc/kubernetes/manifests/
 end script
 
 --====================================
@@ -359,19 +238,14 @@ script
 	set -o errexit
 	set -o nounset
 
-	# Configuration files are located at /etc/saltbase.
+	# Kube-system pod manifest files are located at /run/kube-manifests/kubernetes.
+	. /etc/kube-configure-helper.sh
 	. /etc/kube-env
 	# Fluentd
-	if [ "${ENABLE_NODE_LOGGING:-}" = "true" ]; then
-		if [ "${LOGGING_DESTINATION:-}" = "gcp" ]; then
-			cp /etc/saltbase/kubernetes/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml /etc/kubernetes/manifests/
-		elif [ "${LOGGING_DESTINATION:-}" = "elasticsearch" ]; then
-			cp /etc/saltbase/kubernetes/saltbase/salt/fluentd-es/fluentd-es.yaml /etc/kubernetes/manifests/
-		fi
-	fi
+	start_fluentd
 	# Kube-registry-proxy
 	if [ "${ENABLE_CLUSTER_REGISTRY:-}" = "true" ]; then
-		cp /etc/saltbase/kubernetes/saltbase/salt/kube-registry-proxy/kube-registry-proxy.yaml /etc/kubernetes/manifests/
+		cp /run/kube-manifests/kubernetes/kube-registry-proxy.yaml /etc/kubernetes/manifests/
 	fi
 end script
 
@@ -383,37 +257,23 @@ Content-Disposition: attachment; filename="kube-node-health-monitoring.conf"
 
 description "Kubenetes node health monitoring"
 
-start on stopped kube-docker and started kube-proxy
+start on stopped kube-docker
 
 respawn
 
 script
 	set -o nounset
+	set -o errexit
 
 	# Wait for a minute to let docker, kubelet, and kube-proxy processes finish initialization.
 	# TODO(andyzheng0831): replace it with a more reliable method if possible.
 	sleep 60
-
-	sleep_seconds=10
-	max_seconds=10
-	# We simply kill the process when there is a failure. Another upstart job will automatically
-	# restart the process.
-	while [ 1 ]; do
-		if ! timeout 10 docker version > /dev/null; then
-			echo "Docker daemon failed!"
-			pkill docker
-		fi
-		if ! curl --insecure -m ${max_seconds} -f -s https://127.0.0.1:10250/healthz > /dev/null; then
-			echo "Kubelet is unhealthy!"
-			pkill kubelet
-		fi
-		if ! curl -m ${max_seconds} -f -s http://127.0.0.1:10249/healthz > /dev/null; then
-			echo "Kube-proxy is unhealthy!"
-			pkill kube-proxy
-		fi
-		sleep ${sleep_seconds}
-	done
+	. /etc/kube-configure-helper.sh
+	. /etc/kube-env
+	health_monitoring
 end script
 
---====================================--
+# Wait for 10s to start it again.
+post-stop exec sleep 10
 
+--====================================--
